# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

exclude: ["README.md"] # files to exclude
markdown: kramdown
title: Community-Owned Infrastructure
permalink:
  pretty
sass:
    style: compressed
exclude: ["README.md"] # files to exclude
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Community-Owned Infrastructure

description: "Data and data analytics are spreading fast at higher education institutions, and the academic community is at a critical juncture. "
author:
  name: Scholarly Publishing and Academic Resources Coalition
  email: joe@sparcopen.org
  github: sparcopen
  twitter: sparc_na
  facebook: sparcopen

BASE_PATH: https://josephmcarthur.github.io/infrastructure
#url: http://127.0.0.1:4000/ <!-- Used for Soph's dev

plugins:
  - jekyll-sitemap
